# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [165]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [166]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [167]:
np.zeros(10)+5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [168]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [169]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [170]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [171]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [172]:
np.random.rand(1)

array([0.32164733])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [173]:
np.random.randn(25)


array([ 0.66405224, -0.582604  ,  0.61488906, -0.46808509,  0.128701  ,
        0.699716  ,  0.95983652, -0.3452662 ,  0.26285289,  1.20560453,
        1.0148286 ,  0.16615439,  1.12089782,  0.01648983,  1.50655603,
       -1.95708724,  1.39879857,  1.81000589, -1.97735699,  1.73990996,
        0.53268936, -1.40063031, -0.33824023, -0.64577559, -0.45676365])

#### Create the following matrix:

In [174]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [175]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [176]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [177]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [178]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [179]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [180]:
mat[3][4]

20

20

In [181]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [182]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [183]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [184]:
mat[4]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [185]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [186]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [187]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [188]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [189]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

## Assign the following values
theta_0 = 15; 
theta_1 = 0.2; 
variance=1.2

In [190]:
theta_0 = 15
theta_1 = 0.2
variance = 1.2

## Generate 100 points uniform randomly in range [-50,50] and assign it to X_0

In [4]:
x_0 = np.random.uniform(-50,50,100)
x_0

array([ 33.36708437, -26.32041957,  42.09791782,  42.39849927,
       -44.24639535,   2.69169083,  28.61767855,   1.69275423,
        -9.49782984,   5.17998206,  20.69587979,  15.35419917,
       -36.68594642, -30.20665167, -42.61033921,  39.80553553,
       -42.7892004 , -40.54425887, -45.30821492, -27.09117874,
       -30.89798584,  26.36912573,   2.5059641 ,  16.12700499,
        41.11145466,  48.74265071,   4.67428168, -46.37893034,
       -44.17791092, -12.9487769 ,  -7.84702314, -38.16527444,
       -45.89055017,   3.45325131,  37.62880118, -14.29594878,
       -13.72308449,  -5.28000534,  10.68688322,  34.78587788,
       -31.27416053,  16.75518274,  -3.4283937 ,  28.0223776 ,
        39.9153659 , -44.32277281, -49.83399925,   1.99075348,
         8.17188528, -35.68752685,  41.7021385 , -25.50837986,
        -9.48522282, -46.41393246,  11.91125279,  18.83837957,
       -18.57187283,   4.60566162, -38.65266717,  45.37387675,
       -10.39970201,   2.52719544,  33.15666306,  38.40

## Generate respective y_i normally distributed around theta_0 + theta_1 * x line ('x' are values of X_0) with variance=1.2

In [5]:
line= theta_0+theta_1*x_0
y_i = np.random.normal(line,scale = variance**1/2)

NameError: name 'theta_0' is not defined

## Convert X_0 into array(if it is not) and add 1 from the left to each row

In [6]:
#it should look smth like this
# (1,x1)
# (1,x2)
# .
# .
# .

In [7]:
x_0_reshaped = x_0.reshape(100,1)
x_0_reshaped=np.insert(x_0_reshaped,0,1,axis=1)
x_0_reshaped

array([[  1.        ,  33.36708437],
       [  1.        , -26.32041957],
       [  1.        ,  42.09791782],
       [  1.        ,  42.39849927],
       [  1.        , -44.24639535],
       [  1.        ,   2.69169083],
       [  1.        ,  28.61767855],
       [  1.        ,   1.69275423],
       [  1.        ,  -9.49782984],
       [  1.        ,   5.17998206],
       [  1.        ,  20.69587979],
       [  1.        ,  15.35419917],
       [  1.        , -36.68594642],
       [  1.        , -30.20665167],
       [  1.        , -42.61033921],
       [  1.        ,  39.80553553],
       [  1.        , -42.7892004 ],
       [  1.        , -40.54425887],
       [  1.        , -45.30821492],
       [  1.        , -27.09117874],
       [  1.        , -30.89798584],
       [  1.        ,  26.36912573],
       [  1.        ,   2.5059641 ],
       [  1.        ,  16.12700499],
       [  1.        ,  41.11145466],
       [  1.        ,  48.74265071],
       [  1.        ,   4.67428168],
 

# Great Job!